# Generated by Django 4.2.7 on 2025-04-27 19:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('birthday', 'Birthday Party'), ('festival', 'Festival'), ('product-launch', 'Product Launch'), ('other', 'Other')], max_length=20)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('estimated_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('budget_range', models.CharField(choices=[('5k-10k', '$5,000 - $10,000'), ('10k-25k', '$10,000 - $25,000'), ('25k-50k', '$25,000 - $50,000'), ('50k-100k', '$50,000 - $100,000'), ('100k+', '$100,000+')], max_length=10)),
                ('venue_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Both')], max_length=10)),
                ('theme', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('rustic', 'Rustic'), ('luxury', 'Luxury'), ('custom', 'Custom')], max_length=10)),
                ('special_requirements', models.TextField(blank=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_reference', models.CharField(blank=True, max_length=10, unique=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
