# Generated by Django 4.2.7 on 2025-04-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingForm',
        ),
    ]
