# Generated by Django 4.2.7 on 2025-04-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_delete_bookingform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='budget_range',
            field=models.CharField(choices=[('5k-10k', '₹5,000 - ₹10,000'), ('10k-25k', '₹10,000 - ₹25,000'), ('25k-50k', '₹25,000 - ₹50,000'), ('50k+', '₹50,000+')], max_length=10),
        ),
    ]
